/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginproject2;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class delete extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form delete
     */
    public delete() {
        initComponents();
        
        Toolkit toolkit=getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2- getHeight()/2);
        conn=db.java_db();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mobiles = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        clearrecored = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        gmails = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dobs = new javax.swing.JTextField();
        deleteb = new javax.swing.JButton();
        rmale = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        searchs = new javax.swing.JTextField();
        ids = new javax.swing.JTextField();
        names = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rfemale = new javax.swing.JRadioButton();
        usernames = new javax.swing.JTextField();
        passwords = new javax.swing.JPasswordField();
        compasswords = new javax.swing.JPasswordField();
        picb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Id:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 154, 29));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 154, 32));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("UserName:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 154, 33));

        mobiles.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(mobiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 130, 34));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Password:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 154, 33));

        clearrecored.setBackground(new java.awt.Color(209, 211, 155));
        clearrecored.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        clearrecored.setText("Clear");
        clearrecored.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearrecoredActionPerformed(evt);
            }
        });
        jPanel1.add(clearrecored, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 93, 34));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Comfirm Password:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, 34));

        gmails.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gmails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gmailsActionPerformed(evt);
            }
        });
        jPanel1.add(gmails, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 130, 32));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Mobile No:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 119, 34));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Search ID :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 118, 75, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Gmail ID:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 119, 32));

        dobs.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobsActionPerformed(evt);
            }
        });
        jPanel1.add(dobs, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 130, 30));

        deleteb.setBackground(new java.awt.Color(209, 211, 155));
        deleteb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        deleteb.setText("Delete Record");
        deleteb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebActionPerformed(evt);
            }
        });
        jPanel1.add(deleteb, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, -1, 33));

        rmale.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rmale.setText("Male");
        rmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmaleActionPerformed(evt);
            }
        });
        jPanel1.add(rmale, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Date-of-Birth:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 119, 33));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 89, 34));

        searchs.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        searchs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchs.setToolTipText("");
        searchs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchsActionPerformed(evt);
            }
        });
        searchs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchsKeyReleased(evt);
            }
        });
        jPanel1.add(searchs, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 255, -1));

        ids.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(ids, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 153, 40));

        names.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(names, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 153, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Gender :-");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 119, 33));

        rfemale.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rfemale.setText("Female");
        rfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfemaleActionPerformed(evt);
            }
        });
        jPanel1.add(rfemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, -1, -1));

        usernames.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(usernames, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 150, 30));

        passwords.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        passwords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordsActionPerformed(evt);
            }
        });
        jPanel1.add(passwords, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 150, 30));

        compasswords.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        compasswords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compasswordsActionPerformed(evt);
            }
        });
        jPanel1.add(compasswords, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 150, 30));

        picb.setBackground(new java.awt.Color(240, 246, 145));
        picb.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\my DB fill\\bgimag.png")); // NOI18N
        jPanel1.add(picb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deletebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebActionPerformed
        // TODO add your handling code here:
        try{
            String sql="DELETE FROM user where Id = ?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, ids.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data Deleted Successfully...");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){

            }
        }
    }//GEN-LAST:event_deletebActionPerformed

    private void rmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmaleActionPerformed
        // TODO add your handling code here:

        gender="Male";
        rmale.setSelected(true);
        rfemale.setSelected(false);
    }//GEN-LAST:event_rmaleActionPerformed

    private void searchsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchsActionPerformed

    private void searchsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchsKeyReleased
        // TODO add your handling code here:
        try{
            String sql="select * from user where Id = ?";

            pst=conn.prepareStatement(sql);
            pst.setString(1, searchs.getText());
            rs=pst.executeQuery();

            String add1=rs.getString("Id");
            ids.setText(add1);

            String add2=rs.getString("name");
            names.setText(add2);

            String add3=rs.getString("username");
            usernames.setText(add3);

            String add4=rs.getString("password");
            passwords.setText(add4);

            String add5=rs.getString("compassword");
            compasswords.setText(add5);

            String add6=rs.getString("mobileno");
            mobiles.setText(add6);

            String add7=rs.getString("gmailid");
            gmails.setText(add7);

            String add8=rs.getString("dob");
            dobs.setText(add8);

        }catch(Exception e){

        }
        finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){

            }
        }
    }//GEN-LAST:event_searchsKeyReleased

    private void rfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfemaleActionPerformed
        // TODO add your handling code here:
        gender="Female";
        rfemale.setSelected(true);
        rmale.setSelected(false);
    }//GEN-LAST:event_rfemaleActionPerformed

    private void clearrecoredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearrecoredActionPerformed
        // TODO add your handling code here:
        searchs.setText("");
        ids.setText("");
        names.setText("");
        usernames.setText("");
        passwords.setText("");
        compasswords.setText("");
        mobiles.setText("");
        gmails.setText("");
        dobs.setText("");
    }//GEN-LAST:event_clearrecoredActionPerformed

    private void gmailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gmailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gmailsActionPerformed

    private void dobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fromp j=new fromp();
        j.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void passwordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordsActionPerformed

    private void compasswordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compasswordsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compasswordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearrecored;
    private javax.swing.JPasswordField compasswords;
    private javax.swing.JButton deleteb;
    private javax.swing.JTextField dobs;
    private javax.swing.JTextField gmails;
    private javax.swing.JTextField ids;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mobiles;
    private javax.swing.JTextField names;
    private javax.swing.JPasswordField passwords;
    private javax.swing.JLabel picb;
    private javax.swing.JRadioButton rfemale;
    private javax.swing.JRadioButton rmale;
    private javax.swing.JTextField searchs;
    private javax.swing.JTextField usernames;
    // End of variables declaration//GEN-END:variables
private String gender;
}
